globals:
  - id: dfrobot_sensor_running
    type: bool
    initial_value: 'true'

binary_sensor:
  - platform: gpio
    name: Static Presence
    id: dfrobot_presence
    device_class: occupancy
    disabled_by_default: true
    pin:
      number: GPIO34

uart:
  - id: uart_bus_dfrobot
    tx_pin:
      number: GPIO5
      ignore_strapping_warning: true
    rx_pin:
      number: GPIO15
      ignore_strapping_warning: true
    rx_buffer_size: 512
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);
